### ISSUE TITLE
Invalid link in README-LinkBench.md

### ISSUE THREAD

**Issue by luluxing** [thu-pacman/LiveGraph#1]
Hello! In README-LinkBench.md, the links of "modified LinkBench Java driver" and "C++ driver" are not working.  Could you fix them?
Thank you in advance!

**Comment by saffahyjp** [comment]
Hi luluxing,

Thank you for opening an issue. The modified Java driver and the C++ driver is not open source yet. You may want to use the compiled binary at present. You can find the instructions at https://github.com/thu-pacman/LiveGraph-Binary/blob/master/LinkBench/README.md

**Comment by luluxing** [comment]
Thank you for your quick response! I will use that instead.
